name: trivia_game
description: Original bilingual Arabic and English social trivia game.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/two_pics/redesign/
    - 83A426BC-6461-4BD6-BB12-7877AED62765.png
    - 7E6D631D-725E-465C-86D6-3C6F57959964.png
    - 09F41FAC-F8B2-49DB-A6B4-08D1ACE61399.png
