import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'data/question_model.dart';
import 'data/playable_category_registry.dart';
import 'question_visual.dart';

class BoardCategory{BoardCategory({required this.id,required this.ar,required this.en,required this.icon,required this.questions});final int id;final String ar,en,icon;final List<TriviaQuestion> questions;}
class BoardSlot{BoardSlot({required this.category,required this.points,required this.question});final BoardCategory category;final int points;final TriviaQuestion question;bool used=false;}
BoardCategory categoryForIndex(int i){if(i<0||i>=playableCategories.length)throw ArgumentError('Unknown category index: $i');final c=playableCategories[i];return BoardCategory(id:i,ar:c.ar,en:c.en,icon:c.icon,questions:c.questions);}
List<BoardCategory> categoriesForIndexes(List<int>x)=>x.map(categoryForIndex).toList();
List<BoardSlot> makeSlots(BoardCategory c){final out=<BoardSlot>[];for(final d in QuestionDifficulty.values){final p=c.questions.where((q)=>q.difficulty==d).toList()..shuffle(Random.secure());if(c.id==6&&d==QuestionDifficulty.easy200){final test=p.where((q)=>q.id=='two_pics_001').toList();final rest=p.where((q)=>q.id!='two_pics_001').toList();final chosen=<TriviaQuestion>[...test,...rest].take(2);out.addAll(chosen.map((q)=>BoardSlot(category:c,points:d.points,question:q)));}else{out.addAll(p.take(2).map((q)=>BoardSlot(category:c,points:d.points,question:q)));}}return out;}
class TriviaBoardScreen extends StatefulWidget{const TriviaBoardScreen({super.key,required this.ar,required this.categoryIndexes,required this.teamA,required this.teamB});final bool ar;final List<int>categoryIndexes;final String teamA,teamB;@override State<TriviaBoardScreen>createState()=>_BoardState();}
class _BoardState extends State<TriviaBoardScreen>{late final List<BoardCategory>cats;late final Map<int,List<BoardSlot>>slots;int a=0,b=0,turn=0;@override void initState(){super.initState();cats=categoriesForIndexes(widget.categoryIndexes);slots={for(final c in cats)c.id:makeSlots(c)};SystemChrome.setPreferredOrientations(const[DeviceOrientation.landscapeLeft,DeviceOrientation.landscapeRight]);}@override void dispose(){SystemChrome.setPreferredOrientations(const[DeviceOrientation.portraitUp,DeviceOrientation.portraitDown]);super.dispose();}
@override Widget build(BuildContext context)=>Directionality(textDirection:widget.ar?TextDirection.rtl:TextDirection.ltr,child:Scaffold(appBar:AppBar(toolbarHeight:44,backgroundColor:Colors.transparent,title:Text(widget.ar?'لوحة المواجهة':'Showdown Board')),body:SafeArea(child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[Row(children:[Expanded(child:_score(widget.teamA,a,turn==0)),const SizedBox(width:8),Expanded(child:Text(widget.ar?'الدور على ${turn==0?widget.teamA:widget.teamB}':'${turn==0?widget.teamA:widget.teamB} turn',textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w800))),const SizedBox(width:8),Expanded(child:_score(widget.teamB,b,turn==1))]),const SizedBox(height:10),Expanded(child:LayoutBuilder(builder:(_,box)=>_board(box.maxWidth,box.maxHeight)))])))));
Widget _board(double w,double h){final count=cats.length;final cardW=count==1?min(285.0,w*.54):count==2?min(285.0,(w-32)/2):max(165.0,min(250.0,(w-(count-1)*12)/count));final cardH=min(h*.86,535.0);final row=Row(mainAxisSize:MainAxisSize.min,mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.center,children:[for(int i=0;i<count;i++)...[if(i>0)const SizedBox(width:12),SizedBox(width:cardW,height:cardH,child:_cat(cats[i]))]]);if(count<=2)return Center(child:row);return Center(child:SingleChildScrollView(scrollDirection:Axis.horizontal,child:row));}
Widget _score(String n,int s,bool on)=>Container(padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:const Color(0xFF10434F),borderRadius:BorderRadius.circular(14),border:Border.all(color:on?Colors.white:Colors.transparent,width:2)),child:Text('$n  $s',textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w900)));
Widget _cat(BoardCategory c){final l=slots[c.id]!;Widget cell(BoardSlot s)=>Expanded(child:InkWell(onTap:s.used?null:()=>_open(s),borderRadius:BorderRadius.circular(13),child:Container(margin:const EdgeInsets.all(4),alignment:Alignment.center,decoration:BoxDecoration(color:s.used?Colors.white10:const Color(0xFF064652),borderRadius:BorderRadius.circular(13),border:Border.all(color:s.used?Colors.white10:const Color(0xFF5FD7E5).withValues(alpha:.55))),child:s.used?const Icon(Icons.check_rounded,color:Colors.white30):Text('${s.points}',style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)))));return Container(padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:const Color(0xFF102D39),borderRadius:BorderRadius.circular(20),border:Border.all(color:Colors.white12)),child:Column(children:[Text('${c.icon} ${widget.ar?c.ar:c.en}',textAlign:TextAlign.center,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w900)),const SizedBox(height:5),for(final p in const[200,400,600])Expanded(child:Row(children:[for(final s in l.where((x)=>x.points==p))cell(s)]))]));}
Future<void>_open(BoardSlot s)async{final win=await Navigator.push<int?>(context,MaterialPageRoute(builder:(_)=>TimedQuestionScreen(ar:widget.ar,slot:s,primaryTeam:turn,teamA:widget.teamA,teamB:widget.teamB)));if(!mounted||win==null)return;setState((){s.used=true;if(win==0)a+=s.points;if(win==1)b+=s.points;turn=1-turn;});}}
class TimedQuestionScreen extends StatefulWidget{const TimedQuestionScreen({super.key,required this.ar,required this.slot,required this.primaryTeam,required this.teamA,required this.teamB});final bool ar;final BoardSlot slot;final int primaryTeam;final String teamA,teamB;@override State<TimedQuestionScreen>createState()=>_QuestionState();}
class _QuestionState extends State<TimedQuestionScreen>{Timer?timer;int seconds=60;bool steal=false,revealed=false;int?award;int get active=>steal?1-widget.primaryTeam:widget.primaryTeam;String name(int i)=>i==0?widget.teamA:widget.teamB;@override void initState(){super.initState();_start(60);}@override void dispose(){timer?.cancel();super.dispose();}void _start(int v){timer?.cancel();seconds=v;timer=Timer.periodic(const Duration(seconds:1),(t){if(!mounted){t.cancel();return;}if(seconds<=1){t.cancel();if(!steal){setState((){steal=true;seconds=15;});_start(15);}else{setState((){seconds=0;revealed=true;});}}else{setState(()=>seconds--);}});}void _reveal(){timer?.cancel();setState(()=>revealed=true);}
bool _isMath(String s)=>RegExp(r'\d\s*[+\-×÷*/=]|[+\-×÷*/=]\s*\d|\d\s*[سصxyXY]').hasMatch(s)||s.contains('ناتج')||s.contains('قيمة س')||s.contains('قيمة ص');
String _arabicMath(String s){if(!widget.ar||widget.slot.question.categoryId!='brain'||!_isMath(s))return s;const western='0123456789';const eastern='٠١٢٣٤٥٦٧٨٩';var out=s.replaceAll('س','X').replaceAll('ص','Y');for(var i=0;i<10;i++){out=out.replaceAll(western[i],eastern[i]);}return out;}
@override Widget build(BuildContext context){final q=widget.slot.question;final isPics=q.categoryId=='two_pics';return Directionality(textDirection:widget.ar?TextDirection.rtl:TextDirection.ltr,child:Scaffold(appBar:AppBar(toolbarHeight:46,backgroundColor:Colors.transparent,title:Text('${widget.ar?widget.slot.category.ar:widget.slot.category.en} • ${widget.slot.points}')),body:SafeArea(child:LayoutBuilder(builder:(_,box)=>Stack(children:[PositionedDirectional(start:12,top:8,width:125,height:118,child:_clock()),Positioned.fill(child:Padding(padding:EdgeInsetsDirectional.fromSTEB(box.maxWidth>650?150:14,8,14,12),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:720),child:SingleChildScrollView(child:_content(q,isPics))))))])))));}
Widget _content(TriviaQuestion q,bool isPics){final prompt=widget.ar?q.questionAr:q.questionEn;final answer=widget.ar?q.answerAr:q.answerEn;if(isPics){final first=q.mediaAsset;final second=q.mediaAsset2;final left=widget.ar?second:first;final right=widget.ar?first:second;return Column(mainAxisSize:MainAxisSize.min,children:[Directionality(textDirection:TextDirection.ltr,child:Row(children:[Expanded(child:_pic(left)),const SizedBox(width:12),Expanded(child:_pic(right))])),const SizedBox(height:16),if(revealed)Container(width:double.infinity,padding:const EdgeInsets.symmetric(horizontal:18,vertical:16),decoration:BoxDecoration(color:const Color(0xFF064652),borderRadius:BorderRadius.circular(16),border:Border.all(color:const Color(0xFF5FD7E5))),child:Text(answer,textAlign:TextAlign.center,style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900)))else FilledButton(onPressed:_reveal,child:Text(widget.ar?'إظهار الإجابة':'Show answer')),if(revealed)...[const SizedBox(height:14),_awardButtons()]]);}return Column(mainAxisSize:MainAxisSize.min,children:[QuestionVisual(question:q,ar:widget.ar),const SizedBox(height:14),Text(_arabicMath(prompt),textAlign:TextAlign.center,style:const TextStyle(fontSize:27,fontWeight:FontWeight.w900,height:1.25)),const SizedBox(height:18),if(!revealed)FilledButton(onPressed:_reveal,child:Text(widget.ar?'إظهار الإجابة':'Show answer'))else...[Container(width:double.infinity,padding:const EdgeInsets.symmetric(horizontal:18,vertical:16),decoration:BoxDecoration(color:const Color(0xFF064652),borderRadius:BorderRadius.circular(16),border:Border.all(color:const Color(0xFF5FD7E5))),child:Text(_arabicMath(answer),textAlign:TextAlign.center,style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900))),const SizedBox(height:14),_awardButtons()]]);}
Widget _pic(String? source){if(source==null||source.isEmpty)return _missingPic();final image=source.startsWith('http')?Image.network(source,fit:BoxFit.cover,errorBuilder:(_,__,___)=>_missingPic()):Image.asset(source,fit:BoxFit.cover,errorBuilder:(_,__,___)=>_missingPic());return AspectRatio(aspectRatio:4/3,child:ClipRRect(borderRadius:BorderRadius.circular(18),child:ColoredBox(color:const Color(0xFF142F3A),child:image)));}
Widget _missingPic()=>AspectRatio(aspectRatio:4/3,child:Container(decoration:BoxDecoration(color:const Color(0xFF142F3A),borderRadius:BorderRadius.circular(18)),alignment:Alignment.center,child:const Icon(Icons.hide_image_outlined,size:52,color:Colors.white38)));
Widget _clock()=>Column(mainAxisSize:MainAxisSize.min,children:[SizedBox(width:92,height:92,child:Stack(alignment:Alignment.center,children:[CircularProgressIndicator(value:seconds/(steal?15:60),strokeWidth:5,color:steal?Colors.orangeAccent:const Color(0xFF5FD7E5),backgroundColor:Colors.white12),Text('$seconds',style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900))])),const SizedBox(height:5),Text('${widget.ar?'وقت':'Time'} • ${name(active)}',textAlign:TextAlign.center,maxLines:2,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w800))]);
Widget _awardButtons(){Widget b(String t,int? w)=>OutlinedButton(onPressed:()=>Navigator.pop(context,w),child:Text(t));return Column(children:[Text(widget.ar?'من يستحق ${widget.slot.points} نقطة؟':'Who gets ${widget.slot.points} points?'),const SizedBox(height:8),Wrap(spacing:8,runSpacing:8,alignment:WrapAlignment.center,children:[b(widget.teamA,0),b(widget.teamB,1),b(widget.ar?'لا أحد':'No one',-1)]),const SizedBox(height:10),FilledButton(onPressed:award==null?null:()=>Navigator.pop(context,award),child:Text(widget.ar?'تأكيد':'Confirm'))]);}
}
