import 'dart:async';
import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'data/question_model.dart';
import 'data/questions/uae_general_final.dart';
import 'data/questions/uae_football_final.dart';
import 'data/questions/general_knowledge_final.dart';
import 'data/questions/brain_final.dart';
import 'data/questions/gaming_final.dart';
import 'data/questions/no_words_final.dart';
import 'data/questions/two_pics_final.dart';
import 'question_visual.dart';

class BoardCategory{BoardCategory({required this.id,required this.ar,required this.en,required this.icon,required this.questions});final int id;final String ar,en,icon;final List<TriviaQuestion> questions;}
class BoardSlot{BoardSlot({required this.category,required this.points,required this.question});final BoardCategory category;final int points;final TriviaQuestion question;bool used=false;}
BoardCategory categoryForIndex(int i)=>switch(i){0=>BoardCategory(id:0,ar:'الإمارات',en:'UAE',icon:'🇦🇪',questions:uaeGeneralFinalQuestions),1=>BoardCategory(id:1,ar:'كرة القدم الإماراتية',en:'UAE Football',icon:'⚽',questions:uaeFootballFinalQuestions),2=>BoardCategory(id:2,ar:'معلومات عامة',en:'General Knowledge',icon:'💡',questions:generalKnowledgeFinalQuestions),3=>BoardCategory(id:3,ar:'ألغاز وذكاء',en:'Brain & Riddles',icon:'🧠',questions:brainFinalQuestions),4=>BoardCategory(id:4,ar:'ألعاب الفيديو',en:'Gaming',icon:'🎮',questions:gamingFinalQuestions),5=>BoardCategory(id:5,ar:'ولا كلمة',en:'No Words',icon:'🎯',questions:noWordsFinalQuestions),6=>BoardCategory(id:6,ar:'صورتين كلمة واحدة',en:'Two Pics One Word',icon:'🖼️',questions:twoPicsFinalQuestions),_=>throw ArgumentError('Unknown category index: $i')};
List<BoardCategory> categoriesForIndexes(List<int>x)=>x.map(categoryForIndex).toList();
List<BoardSlot> makeSlots(BoardCategory c){final out=<BoardSlot>[];for(final d in QuestionDifficulty.values){final p=c.questions.where((q)=>q.difficulty==d).toList()..shuffle(Random.secure());out.addAll(p.take(2).map((q)=>BoardSlot(category:c,points:d.points,question:q)));}return out;}
class TriviaBoardScreen extends StatefulWidget{const TriviaBoardScreen({super.key,required this.ar,required this.categoryIndexes,required this.teamA,required this.teamB});final bool ar;final List<int>categoryIndexes;final String teamA,teamB;@override State<TriviaBoardScreen>createState()=>_BoardState();}
class _BoardState extends State<TriviaBoardScreen>{late final List<BoardCategory>cats;late final Map<int,List<BoardSlot>>slots;int a=0,b=0,turn=0;@override void initState(){super.initState();cats=categoriesForIndexes(widget.categoryIndexes);slots={for(final c in cats)c.id:makeSlots(c)};SystemChrome.setPreferredOrientations(const[DeviceOrientation.landscapeLeft,DeviceOrientation.landscapeRight]);}@override void dispose(){SystemChrome.setPreferredOrientations(const[DeviceOrientation.portraitUp,DeviceOrientation.portraitDown]);super.dispose();}
@override Widget build(BuildContext context)=>Directionality(textDirection:widget.ar?TextDirection.rtl:TextDirection.ltr,child:Scaffold(appBar:AppBar(toolbarHeight:44,backgroundColor:Colors.transparent,title:Text(widget.ar?'لوحة المواجهة':'Showdown Board')),body:SafeArea(child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[Row(children:[Expanded(child:_score(widget.teamA,a,turn==0)),const SizedBox(width:8),Expanded(child:Text(widget.ar?'الدور على ${turn==0?widget.teamA:widget.teamB}':'${turn==0?widget.teamA:widget.teamB} turn',textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w800))),const SizedBox(width:8),Expanded(child:_score(widget.teamB,b,turn==1))]),const SizedBox(height:10),Expanded(child:LayoutBuilder(builder:(_,box)=>_board(box.maxWidth,box.maxHeight)))])))));
Widget _board(double w,double h){final count=cats.length;final cardW=count==1?min(285.0,w*.54):count==2?min(285.0,(w-32)/2):max(165.0,min(250.0,(w-(count-1)*12)/count));final cardH=min(h*.86,535.0);final row=Row(mainAxisSize:MainAxisSize.min,mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.center,children:[for(int i=0;i<count;i++)...[if(i>0)const SizedBox(width:12),SizedBox(width:cardW,height:cardH,child:_cat(cats[i]))]]);if(count<=2)return Center(child:row);return Center(child:SingleChildScrollView(scrollDirection:Axis.horizontal,child:row));}
Widget _score(String n,int s,bool on)=>Container(padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:const Color(0xFFD3A52F),borderRadius:BorderRadius.circular(14),border:Border.all(color:on?Colors.white:Colors.transparent,width:2)),child:Text('$n  $s',textAlign:TextAlign.center,style:const TextStyle(fontWeight:FontWeight.w900)));
Widget _cat(BoardCategory c){final l=slots[c.id]!;Widget cell(BoardSlot s)=>Expanded(child:InkWell(onTap:s.used?null:()=>_open(s),borderRadius:BorderRadius.circular(13),child:Container(margin:const EdgeInsets.all(4),alignment:Alignment.center,decoration:BoxDecoration(color:s.used?Colors.white10:const Color(0xFF654CFF),borderRadius:BorderRadius.circular(13),border:Border.all(color:s.used?Colors.white10:const Color(0xFF806EFF).withValues(alpha:.55))),child:s.used?const Icon(Icons.check_rounded,color:Colors.white30):Text('${s.points}',style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)))));return Container(padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:const Color(0xFF131620),borderRadius:BorderRadius.circular(20),border:Border.all(color:Colors.white12)),child:Column(children:[Text('${c.icon} ${widget.ar?c.ar:c.en}',textAlign:TextAlign.center,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w900)),const SizedBox(height:5),for(final p in const[200,400,600])Expanded(child:Row(children:[for(final s in l.where((x)=>x.points==p))cell(s)]))]));}
Future<void>_open(BoardSlot s)async{final win=await Navigator.push<int?>(context,MaterialPageRoute(builder:(_)=>TimedQuestionScreen(ar:widget.ar,slot:s,primaryTeam:turn,teamA:widget.teamA,teamB:widget.teamB)));if(!mounted||win==null)return;setState((){s.used=true;if(win==0)a+=s.points;if(win==1)b+=s.points;turn=1-turn;});}}
class TimedQuestionScreen extends StatefulWidget{const TimedQuestionScreen({super.key,required this.ar,required this.slot,required this.primaryTeam,required this.teamA,required this.teamB});final bool ar;final BoardSlot slot;final int primaryTeam;final String teamA,teamB;@override State<TimedQuestionScreen>createState()=>_QuestionState();}
class _QuestionState extends State<TimedQuestionScreen>{Timer?timer;int seconds=60;bool steal=false,revealed=false;int?award;int get active=>steal?1-widget.primaryTeam:widget.primaryTeam;String name(int i)=>i==0?widget.teamA:widget.teamB;@override void initState(){super.initState();_start(60);}@override void dispose(){timer?.cancel();super.dispose();}void _start(int v){timer?.cancel();seconds=v;timer=Timer.periodic(const Duration(seconds:1),(t){if(!mounted){t.cancel();return;}if(seconds<=1){t.cancel();if(!steal){setState((){steal=true;seconds=15;});_start(15);}else{setState((){seconds=0;revealed=true;});}}else{setState(()=>seconds--);}});}void _reveal(){timer?.cancel();setState(()=>revealed=true);}
bool _isMath(String s)=>RegExp(r'\d\s*[+\-×÷*/=]|[+\-×÷*/=]\s*\d|\d\s*[سصxyXY]').hasMatch(s)||s.contains('ناتج')||s.contains('قيمة س')||s.contains('قيمة ص');
String _arabicMath(String s){if(!widget.ar||widget.slot.question.categoryId!='brain'||!_isMath(s))return s;const western='0123456789';const eastern='٠١٢٣٤٥٦٧٨٩';var out=s.replaceAll('س','X').replaceAll('ص','Y');for(var i=0;i<10;i++){out=out.replaceAll(western[i],eastern[i]);}return out;}
@override
Widget build(BuildContext context){
 final q=widget.slot.question;
 final isPics=q.categoryId=='two_pics';
 return Directionality(
  textDirection:widget.ar?TextDirection.rtl:TextDirection.ltr,
  child:Scaffold(
   appBar:AppBar(toolbarHeight:46,backgroundColor:Colors.transparent,title:Text('${widget.ar?widget.slot.category.ar:widget.slot.category.en} • ${widget.slot.points}')),
   body:SafeArea(
    child:LayoutBuilder(
     builder:(_,box){
      return Stack(children:[
       PositionedDirectional(start:12,top:8,width:125,height:118,child:_clock()),
       Positioned.fill(child:Padding(padding:EdgeInsetsDirectional.fromSTEB(box.maxWidth>650?150:14,8,14,12),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:720),child:SingleChildScrollView(child:_content(q,isPics))))))),
      ]);
     },
    ),
   ),
  ),
 );
}
Widget _clock()=>Column(children:[Container(width:78,height:78,alignment:Alignment.center,decoration:BoxDecoration(shape:BoxShape.circle,color:const Color(0xFF151721),border:Border.all(color:steal?const Color(0xFFFFA34D):const Color(0xFF43D5C7),width:4)),child:Text('$seconds',style:const TextStyle(fontSize:27,fontWeight:FontWeight.w900))),const SizedBox(height:4),Text('${steal?(widget.ar?'سرقة':'STEAL'):(widget.ar?'وقت':'TIME')} • ${name(active)}',textAlign:TextAlign.center,maxLines:2,style:const TextStyle(fontSize:10,fontWeight:FontWeight.w900))]);
Widget _photoFallback()=>Container(color:const Color(0xFF171923),alignment:Alignment.center,child:const Icon(Icons.image_not_supported_outlined,size:38,color:Colors.white38));
Widget _photo(String source){final network=source.startsWith('http://')||source.startsWith('https://');final image=network?Image.network(source,fit:BoxFit.cover,width:double.infinity,height:double.infinity,filterQuality:FilterQuality.medium,webHtmlElementStrategy:WebHtmlElementStrategy.fallback,loadingBuilder:(context,child,progress)=>progress==null?child:Container(color:const Color(0xFF171923),alignment:Alignment.center,child:const CircularProgressIndicator(strokeWidth:2)),errorBuilder:(_,__,___)=>_photoFallback()):Image.asset(source,fit:BoxFit.cover,width:double.infinity,height:double.infinity,filterQuality:FilterQuality.medium,errorBuilder:(_,__,___)=>_photoFallback());return ClipRRect(borderRadius:BorderRadius.circular(20),child:AspectRatio(aspectRatio:4/3,child:image));}
Widget _twoPics(TriviaQuestion q){final a=q.mediaAsset,b=q.mediaAsset2;if(a==null||b==null)return Container(width:double.infinity,padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:const Color(0xFF171923),borderRadius:BorderRadius.circular(22),border:Border.all(color:Colors.white12)),child:Text(widget.ar?'يتم تجهيز الصور الواقعية لهذا اللغز':'Real photos are being prepared for this puzzle',textAlign:TextAlign.center,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w800)));return Row(children:[Expanded(child:_photo(a)),const SizedBox(width:12),Expanded(child:_photo(b))]);}
Widget _content(TriviaQuestion q,bool isPics){final rawQ=widget.ar?q.questionAr:q.questionEn,rawA=widget.ar?q.answerAr:q.answerEn;final shownQ=_arabicMath(rawQ),shownA=_arabicMath(rawA);return Column(mainAxisSize:MainAxisSize.min,children:[if(isPics)...[_twoPics(q),const SizedBox(height:15)]else...[QuestionVisual(question:q,ar:widget.ar),const SizedBox(height:14),Text(shownQ,textAlign:TextAlign.center,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900,height:1.25)),const SizedBox(height:15)],if(revealed)Container(width:double.infinity,padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:const Color(0xFF211C48),borderRadius:BorderRadius.circular(16),border:Border.all(color:const Color(0xFF6D5CE7))),child:Text(shownA,textAlign:TextAlign.center,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900))),const SizedBox(height:12),if(!revealed)SizedBox(width:220,height:45,child:FilledButton(onPressed:_reveal,child:Text(widget.ar?'إظهار الإجابة':'Show answer'))),if(revealed)...[Text(widget.ar?'من يستحق ${widget.slot.points} نقطة؟':'Who gets ${widget.slot.points} points?'),const SizedBox(height:7),Row(children:[Expanded(child:_award(0,widget.teamA)),const SizedBox(width:6),Expanded(child:_award(1,widget.teamB)),const SizedBox(width:6),Expanded(child:_award(-1,widget.ar?'لا أحد':'Nobody'))]),const SizedBox(height:8),FilledButton(onPressed:award==null?null:()=>Navigator.pop(context,award),child:Text(widget.ar?'تأكيد':'Confirm'))]]);}
Widget _award(int v,String label)=>OutlinedButton(onPressed:()=>setState(()=>award=v),style:OutlinedButton.styleFrom(backgroundColor:award==v?const Color(0xFF5C4ED8):const Color(0xFF171923)),child:Text(label,maxLines:1,overflow:TextOverflow.ellipsis));}
