const fs=require('fs'),dir='content/kuwait_general/';
function set(tier,id,fact,source,ar,en,aa,ae){let lines=fs.readFileSync(dir+tier+'.psv','utf8').trim().split(/\r?\n/);let i=lines.findIndex(x=>x.startsWith(id+'|'));if(i<0)throw Error(id);lines[i]=[id,fact,source,ar,en,aa,ae].join('|');fs.writeFileSync(dir+tier+'.psv',lines.join('\n')+'\n');}
fs.appendFileSync(dir+'sources.psv','ramsar|Ramsar Secretariat — Kuwait accession and first designated site|https://www.ramsar.org/news/state-kuwait-becomes-169th-contracting-party-ramsar-convention-wetlands|MubarakAlKabeerReserve onBoubyan KuwaitfirstRamsarsite2015; worlds largest breedingcolony CrabPlover; twobirdmigrationroutesEurasiaAfrica TurkeyIndia; nurserycommercialfish.\n'+
'club2009|AFC — Al Ajmi strikes again|https://www.the-afc.com/en/club/afc_cup/news/al_ajmi_strikes_again.html|IsmailAlAjmi Omaninternational scoredwinninggoalKuwaitSportsClub2009AFCCuptitle; laterKazma. Page migrationdate2021 doesnotmatch archived2011/12context; ask2009factonly.\n');
set('easy','003','science:kfas:identity','kfas','ما اسم المؤسسة الكويتية التي أُنشئت لدعم التقدم العلمي عام 1976؟','Which Kuwaiti foundation was established in 1976 to support scientific advancement?','مؤسسة الكويت للتقدم العلمي','Kuwait Foundation for the Advancement of Sciences');
set('easy','012','flag:lowerstripe:colour','factsheet','ما لون الشريط الأفقي السفلي في علم الكويت؟','What colour is the bottom horizontal stripe of Kuwait\'s flag?','الأحمر','Red');
set('easy','013','currency:banknotes:minimum','currency','ما أصغر فئة من الأوراق النقدية الكويتية؟','What is the smallest denomination of Kuwaiti banknotes?','ربع دينار','A quarter dinar');
set('easy','036','food:ogaily:flavour','culinary','ما التابل الذهبي الذي يلوّن قرص عقيلي ويمنحه نكهته المميزة؟','Which golden spice colours Gers Ogaily and gives it its distinctive flavour?','الزعفران','Saffron');
set('easy','067','clothing:bushiya:function','customs','أي جزء من الجسم تغطيه البوشية في الملابس النسائية الكويتية التقليدية؟','Which part of the body does the Bushiya cover in traditional Kuwaiti women\'s clothing?','الوجه','The face');
set('medium','103','nature:mubarakreserve:island','ramsar','على أي جزيرة تقع محمية مبارك الكبير المسجّلة ضمن مواقع رامسار؟','On which island is the Ramsar-listed Mubarak Al-Kabeer Reserve located?','بوبيان','Bubiyan');
set('hard','148','football:club2009:winninggoalscorer','club2009','من اللاعب العُماني الذي سجّل هدف تتويج نادي الكويت بكأس الاتحاد الآسيوي عام 2009؟','Which Omani player scored the goal that won Kuwait SC the 2009 AFC Cup?','إسماعيل العجمي','Ismail Al-Ajmi');
set('hard','165','archaeology:tellsaid:hybridorders','failaka','أي تقليدين معماريين اجتمعا في تيجان أعمدة معبد تل سعيد وقواعدها؟','Which two architectural traditions were combined in Tell Said temple\'s column capitals and bases?','تيجان يونانية أيونية وقواعد فارسية','Greek Ionic capitals and Persian bases');
set('hard','166','nature:mubarakreserve:crabplover','ramsar','أي طائر تستضيف محمية مبارك الكبير أكبر مستعمرة تكاثر له في العالم، وفق رامسار؟','Which bird has its world\'s largest breeding colony in Mubarak Al-Kabeer Reserve, according to Ramsar?','حنكور (زقزاق السرطان)','Crab plover');
set('hard','203','towers:secondary:pairedinspiration','towers','ما الأداتان التقليديتان اللتان ألهمتا شكلي البرج الأوسط وأصغر برج في أبراج الكويت، على الترتيب؟','Which traditional objects inspired the middle and smallest Kuwait Towers, respectively?','المرش والمكحلة','A perfume sprinkler and a kohl container');
set('hard','204','nature:mubarakreserve:flyway','ramsar','إلى جانب طريق أوراسيا–أفريقيا، بين أي بلدين يمتد طريق هجرة الطيور الآخر عبر محمية مبارك الكبير؟','Besides the Eurasia–Africa route, between which two countries does the other bird migration route through Mubarak Al-Kabeer Reserve run?','تركيا والهند','Turkey and India');
console.log('Editorial corrections applied without changing completed categories.');
