const fs=require('fs'),path=require('path');
const dir=path.resolve(__dirname,'../content/serie_a');
let hard=fs.readFileSync(path.join(dir,'hard.psv'),'utf8').replace('award:quagliarella:earliestclubwinner','award:samp1961:firstcapocannoniere');fs.writeFileSync(path.join(dir,'hard.psv'),hard);
let text=fs.readFileSync(path.resolve(__dirname,'record_la_liga_editorial_review.js'),'utf8').replaceAll('la_liga','serie_a').replaceAll('La Liga','Serie A');
const reasons={
attack:'Sampdoria Goal Twins, Milan Gre-No-Li and Genoa Aguilera-Skuhravy identify three different attacking partnerships; no member-by-member reverse questions.',
award:'Different recipients, seasons and awards. Kaka 2007, Weah 1995 and Nedved 2003 Ballons d Or differ from Baresi podium place in 1989. Totti Golden Shoe differs from Roma career goals. Bierhoff 1998 and Amoroso 1999 concern separate Udinese winners. Kvaratskhelia league MVP and McTominay AIC award are different institutions and seasons. Fiorentina Toni 2006 goals differ from Verona Toni oldest top scorer 2015. Dzeko, Lucarelli, Inzaghi, Nielsen, Brighenti, Protti and Hubner concern different clubs and campaigns, each queried once.',
coach:'Separate appointments, clubs, campaigns or milestones. Conte Inter 2021 and Napoli 2025 are different titles; Juventus unbeaten 2012 asks club rather than either of those titles. Pioli, Mourinho, Spalletti, Simone Inzaghi, Allegri, Herrera, Sacchi, Gasperini, Boskov, Zaccheroni, Scala, Italiano, Di Francesco, Maestrelli, Eriksson, Sarri, Deschamps, Malesani, Lippi, Del Neri, Shevchenko, Scopigno, Tabanelli, Bianchi, Guidolin and Cagni each have an independently sourced specific achievement. Scala promotion/first cup is not Malesani 1999 double.',
derby:'Madonnina, capital, Lanterna and Mole identify different club pairings. Milan derby statue origin, first meeting in Chiasso and first competitive meeting abroad in Beijing are different historical attributes; no inverse city or club identification.',
europe:'Parma 1999 winning team identification and Dino Baggio both-leg scoring in 1995 are different campaigns; neither repeats the Malesani coaching question.',
family:'Cesare Maldini father relation differs from Paolo debut coach Liedholm; no reversed father/son question.',
final:'Lookman 2024 scorer, Lulic 2013 scorer, Petkovic 2013 coach, Gardoni 1963 captain and Ndoye 2025 Player of the Match are different roles. Domenghini 1963 hat-trick and Tabanelli coach differ from captain Gardoni; no reverse scorer question.',
history:'Distinct club origins, debuts, moves and historical milestones. First single-group champion, founding season and first leading scorer query different attributes; Genoa 1898 is the earlier national format. Buffon first club and debut opponent are different relations. Totti armband predecessor, debut and farewell are three different events. Lazio colour inspiration differs from eagle crest and flying eagle name. Torino Superga year and final friendly opponent differ. Sassuolo European debut differs from first Juventus victory. Academy Pirlo differs from Ancelotti role change. Ronaldo arrival year differs from first shirt number. No current youngest-appearance claim attached to Amadei.',
identity:'Distinct clubs and players. Present Juventus colours, former pink and Notts County inspiration measure separate aspects. Lazio eagle image, Olympia bird name and Greek colours inspiration differ. Milan and Roma nickname colours concern different teams. Riva nickname differs from retired shirt. Baresi retired six differs from 1989 award podium. Bergomi Zio differs from debut competition. Dybala nickname differs from Palermo transfer; Cavani nickname differs from his move and Maradona move. Zanetti shirt differs from appearance record and Banfield origin.',
kit:'Palermo pink/black and Torino maroon concern two independent club identities; neither copies Juventus original pink.',
match:'Independent matches and actions. Atalanta 1963 Coppa final hat-trick differs from 2024 Europa final hat-trick. Milito Siena title winner and Genoa derby hat-trick are different games; Samuel Siena comeback winner is January rather than May 2010. Inter 2024 opponent and Acerbi opening scorer are distinct roles. Higuain final-day Frosinone opponent differs from the joint season record identity. Berardi four, Klose five, Mihajlovic free-kick hat-trick, Stankovic halfway volley, Serginho derby contribution, Calori upset, Sansone first Juventus win, Vieri debut hat-trick, Virdis decisive brace, Recoba debut brace and Chinaglia clinching penalty each query one unique action.',
player:'Cavani, Seedorf, Marchisio and De Rossi nickname identification concerns different players. Torricelli furniture employment and Rossi Vicenza 1978 club concern different careers; no inverse career clue.',
record:'Different metrics and subjects. Club career goal/app records do not repeat player nicknames or transfer origins. Piola league career differs from Higuain/Immobile single season; Juventus points, perfect home record and nine consecutive titles differ. Chiellini nine-season participation differs from title count. Buffon prior record holder and Belotti streak-ending scorer are different roles. Protti three divisions differs from Bari 1996 award. Milan 58 unbeaten differs from Juventus unbeaten season. No routine multiple copies of the same record.',
role:'Ancelotti changing Pirlo tactical role differs from Pirlo Brescia academy and Chelsea title coaching in Premier League.',
rule:'Ten-title shirt star and three-point-win introduction are separate rules; title count queries do not reverse either.',
season:'Juventus unbeaten 2012 identifies that campaign; no reverse coach or undefeated match-count question.',
stadium:'Distinct clubs and attributes. Napoli Maradona namesake differs from his Barcelona transfer and first title year. Parma Tardini home identification differs from promotion opponent Reggiana. San Siro Meazza namesake is queried once. Roma home agreement, Bologna president namesake and earlier Littoriale name, Fiorentina UEFA president, Lecce home, Cagliari 1970 ground and Juventus first competitive scorer are separate facts.',
term:'Capocannoniere meaning is the generic award criterion; winner questions concern separately sourced achievements.',
title:'Different championships and roles. Cagliari club, Scopigno coach, Amsicora ground and Bari clincher are distinct attributes. Verona club, Garella cross-club keeper and Atalanta clincher differ. Bologna 1964 opponent, coach and leading scorer concern separate roles. Lazio Maestrelli coach, Wilson captain and Chinaglia winning scorer differ. Roma Capello 2001 differs from Capello Real Madrid achievements.',
transfer:'Maradona Barcelona-to-Napoli 1984 and Seedorf-Coco exchange 2002 are different moves; no inverse destination or transfer-year question.'
};
text=text.replace(/const reasons=\{[\s\S]*?\n\};/, 'const reasons='+JSON.stringify(reasons,null,2)+';');
fs.writeFileSync(path.resolve(__dirname,'record_serie_a_editorial_review.js'),text);
