// Archive completed human source, bilingual, difficulty and semantic review.
// Explicit candidate decisions are stored separately and new pairs fail closed.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const data=path.resolve(__dirname,'../content/bundesliga');
function psv(file){const lines=fs.readFileSync(path.join(data,file),'utf8').trim().split(/\r?\n/),keys=lines.shift().replace(/^\uFEFF/,'').split('|');return lines.filter(Boolean).map(l=>Object.fromEntries(l.split('|').map((v,i)=>[keys[i],v])));}
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function csv(name,rows,keys){fs.writeFileSync(path.join(data,name),[keys,...rows.map(r=>keys.map(k=>r[k]??''))].map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n')+'\n');}
const sources=Object.fromEntries(psv('sources.psv').map(s=>[s.key,s]));
const rows=['easy','medium','hard'].flatMap(tier=>psv(tier+'.psv').map(q=>({...q,tier})));
function editorialHash(q){const s=sources[q.source];return hash([q.id,q.tier,q.factKey,q.source,q.questionAr,q.questionEn,q.answerAr,q.answerEn,s.name,s.url,s.evidence].join('\n'));}
const reasons={
  "history": "Reviewed individual facts: history:bundesliga:firstchampion; history:hamburg:everpresentuntil2018; history:leverkusen:factoryindustry; history:hertha:steamboatname; history:nuremberg:relegatedchampion; history:leipzig:playingrights; history:konietzka:firstgoal. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "record": "Reviewed individual facts: record:bundesliga:careergoals; record:bayern:eleventitles; record:lewandowski:season41; record:fastest:jointscorers; record:gladbach:largestwin; record:zorc:dortmundappearances; record:hildebrand:884minutes; record:korbel:602appearances; record:butt:scoringkeeper; record:kirsten:bayergoals; record:dardai:herthaappearances; record:allgower:stuttgart; record:diouf:earliestsecondyellow. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "coach": "Reviewed individual facts: coach:leverkusen:2024; coach:dortmund:kloppdouble; coach:bayern:flicksextuple; coach:klopp:mainzpromotion; coach:nagelsmann:youngappointment; coach:heynckes:2013treble; coach:gladbach:weisweiler; coach:bremen:2004double; coach:frankfurt:2022europe; coach:hoffenheim:backtobackpromotion; coach:wolfsburg:2009; coach:rehhagel:kingotto; coach:veh:2007title; coach:union:firstpromotion; coach:koln:firsttitle; coach:dortmund:2002; coach:freiburg:finkepromotion; coach:tuchel:mainzyouthtitle; coach:mainz:promotion2009; coach:munich1860:1966; coach:mclaren:firstenglish. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "stadium": "Reviewed individual facts: stadium:dortmund:yellowwall; stadium:hertha:olympiastadion; stadium:bremen:weserriver; stadium:lautern:walternamesake; stadium:union:alteforsterei; stadium:nuremberg:morlocknamesake; stadium:westfalen:firstleaguefixture; stadium:gladbach:formerhome; stadium:hamburg:footstatue; stadium:allianz:firstopeningopponent. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "derby": "Reviewed individual facts: derby:revier:clubs. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "nickname": "Reviewed individual facts: nickname:gladbach:foals; nickname:leverkusen:werkself; nickname:leipzig:redbulls; nickname:beckenbauer:kaiser; nickname:thomasmuller:raumdeuter; nickname:kahn:titan; nickname:podolski:prinzpoldi; nickname:schalke:miners; nickname:hertha:oldlady; nickname:cherundolo:captainamerica. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "player": "Reviewed individual facts: player:neuer:schalkeacademy; player:kimmich:stuttgartacademy; player:son:bundesidentity; player:davies:canada; player:kagawa:japan; player:beckenbauer:hamburgreturn; player:compper:firsthoffenheimcap; player:haller:augsburgreturn. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "title": "Reviewed individual facts: title:kaiserslautern:promotedchampion. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "rule": "Reviewed individual facts: rule:fiftyplusone:voting; rule:threepoints:firstseason. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "kit": "Reviewed individual facts: kit:stuttgart:redhoop. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "crest": "Reviewed individual facts: crest:frankfurt:eagle. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "attack": "Reviewed individual facts: attack:wolfsburg:2009duo; attack:bayern:robbery; attack:stuttgart:magictriangle; attack:frankfurt:buffaloherd. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "business": "Reviewed individual facts: business:wolfsburg:volkswagen; business:hopp:sap. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "culture": "Reviewed individual facts: culture:union:christmassongs; culture:union:bleedfundraiser. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "match": "Reviewed individual facts: match:haaland:debutscorer; match:lewandowski:fiveinnine; match:okocha:kahnslalom; match:stuttgart2007:clinchscorer; match:naldo:derbyequaliser2017; match:kiessling:ghostgoal2013; match:dietermuller:sixgoals; match:stoppelkamp:82metres; match:gladbach1971:brokenpost; match:lautern1973:pirrungbrace; match:bayern:firstleagueopponent; match:bayer2000:finaldayopponent; match:hanke:buttkickofflob; match:augsburg2011:promotionwinner; match:hertha1969:attendanceopponent; match:hannover2009:threeowngoals; match:helmer:ghostgoal1994; match:robbery:firstsharedopponent. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "transfer": "Reviewed individual facts: transfer:raul:schalke2010; transfer:kane:bayerntottenham; transfer:reus:gladbach2012; transfer:kahn:karlsruhe. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "trophy": "Reviewed individual facts: trophy:bundesliga:meisterschale; trophy:meisterschale:designer; trophy:meisterschale:predecessor. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "award": "Reviewed individual facts: award:torjagerkanone:criterion; award:seeler:firsttopscorer; award:grafite:2009; award:huntelaar:2012; award:meier:2015. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "cologne": "Reviewed individual facts: cologne:mascot:animal. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "duisburg": "Reviewed individual facts: duisburg:nickname:zebras; duisburg:1963:anthem. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "darmstadt": "Reviewed individual facts: darmstadt:nickname:lilies; darmstadt:2016:stadiumtribute; darmstadt:1978:training. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "marmoush": "Reviewed individual facts: marmoush:frankfurt:egypt; marmoush:academy:wadidegla. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "hakimi": "Reviewed individual facts: hakimi:dortmund:nation. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "streich": "Reviewed individual facts: streich:freiburg:longtenure; streich:2023:antidiscriminationprize. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "dortmund": "Reviewed individual facts: dortmund:emma:animal. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "hamburg": "Reviewed individual facts: hamburg:cityrival:stpauli. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "stpauli": "Reviewed individual facts: stpauli:fans:piratesymbol; stpauli:stadium:millerntor; stpauli:fans:treewatchers. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "sane": "Reviewed individual facts: sane:schalke:development. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "musiala": "Reviewed individual facts: musiala:youth:nation; musiala:academy:chelsea. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "auba": "Reviewed individual facts: auba:dortmund:superheromasks. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "bellingham": "Reviewed individual facts: bellingham:origin:birmingham; bellingham:captain:2022. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "moukoko": "Reviewed individual facts: moukoko:debut:16. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "pizarro": "Reviewed individual facts: pizarro:oldestscorer:2019. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "format": "Reviewed individual facts: format:current:teamcount. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "klose": "Reviewed individual facts: klose:nickname:salto. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "dortmund1995": "Reviewed individual facts: dortmund1995:1996:coach. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "alaba": "Reviewed individual facts: alaba:nation:austria. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "dortmund2017": "Reviewed individual facts: dortmund2017:cup:coach. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "bayern2013": "Reviewed individual facts: bayern2013:thiago:origin; bayern2013:guardiola:appointment. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "bayern2024": "Reviewed individual facts: bayern2024:kompany:appointment. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "ribery2007": "Reviewed individual facts: ribery2007:origin:marseille. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "robben2009": "Reviewed individual facts: robben2009:origin:real. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "wirtz": "Reviewed individual facts: wirtz:2024:playerseason. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "europe": "Reviewed individual facts: europe:mainz:fairplay2005; europe:augsburg:2016opponent. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "family": "Reviewed individual facts: family:boateng:herthabrothers. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "makaay": "Reviewed individual facts: makaay:nickname:phantom; makaay:bayern:3000thgoal. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "gladbach1977": "Reviewed individual facts: gladbach1977:ballondor. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "karlsruhe1990s": "Reviewed individual facts: karlsruhe1990s:coach:schafer. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "bayern2001": "Reviewed individual facts: bayern2001:titleclinchscorer. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "goretzka": "Reviewed individual facts: goretzka:youthclub. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "cottbus": "Reviewed individual facts: cottbus:2001:foreignXI. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "kiel": "Reviewed individual facts: kiel:nickname:storks. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "heidenheim": "Reviewed individual facts: heidenheim:firstpromotion:coach; heidenheim:firsteurope:competition; heidenheim:voith:altitude. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "karlsruhe": "Reviewed individual facts: karlsruhe:scholl:youthclub. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "fortuna": "Reviewed individual facts: fortuna:allofs:brothers; fortuna:free:initiative; fortuna:name:breadcarriage; fortuna:appearance:zewe. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "lewandowski": "Reviewed individual facts: lewandowski:2010:origin. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "lahm": "Reviewed individual facts: lahm:loan:stuttgart. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "klinsmann": "Reviewed individual facts: klinsmann:trade:baker; klinsmann:usa:alias. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "leipzig": "Reviewed individual facts: leipzig:rb:expansion. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "bayer1988": "Reviewed individual facts: bayer1988:final:opponent; bayer1988:aggregateequaliser; bayer1988:shootout:keeper. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "stuttgart1992": "Reviewed individual facts: stuttgart1992:title:coach. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "alaba2011": "Reviewed individual facts: alaba2011:loan:hoffenheim. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "freiburg2024": "Reviewed individual facts: freiburg2024:coachsuccession. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "petersen": "Reviewed individual facts: petersen:substitutegoals:34. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "diego2007": "Reviewed individual facts: diego2007:aachen:longgoal. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "lehmann1997": "Reviewed individual facts: lehmann1997:openplaygoal. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "wolfsburg2015": "Reviewed individual facts: wolfsburg2015:assistmaker. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "language": "Reviewed individual facts: language:werder:riverisland; language:eintracht:unity. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "final": "Reviewed individual facts: final:bremen2009:ozilwinner. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "bochum": "Reviewed individual facts: bochum:anthem:artist. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "mascot": "Reviewed individual facts: mascot:frankfurt:attila. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "training": "Reviewed individual facts: training:wolfsburg:mountmagath. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "cup": "Reviewed individual facts: cup:ulm:nurembergupset2001. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "technology": "Reviewed individual facts: technology:goalline:firstseason. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "stuttgart2006": "Reviewed individual facts: stuttgart2006:vehpredecessor. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "title2001": "Reviewed individual facts: title2001:keeper:schober. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "hennes": "Reviewed individual facts: hennes:1950:donor. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "emma": "Reviewed individual facts: emma:namesake:emmerich. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "karlsruhe1994": "Reviewed individual facts: karlsruhe1994:semifinal:opponent. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "stpauli2003": "Reviewed individual facts: stpauli2003:rescue:shirtword. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "fortuna1978": "Reviewed individual facts: fortuna1978:bayern:score. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "reus": "Reviewed individual facts: reus:2015:robinmask. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "lautern1991": "Reviewed individual facts: lautern1991:title:coach. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "supercup1995": "Reviewed individual facts: supercup1995:dortmund:scorer. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "bayern": "Reviewed individual facts: bayern:firstspanishplayer. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "alonso2014": "Reviewed individual facts: alonso2014:cologne:touches. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "fichtel": "Reviewed individual facts: fichtel:43:appearance. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.",
  "stuttgart2007": "Reviewed individual facts: stuttgart2007:mexicanpair. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families."
};
const families=[];
for(const[entity,members]of Map.groupBy(rows,q=>q.factKey.split(':')[0])){members.sort((a,b)=>a.id.localeCompare(b.id));if(!reasons[entity])throw Error('Missing family '+entity);families.push({entity,ids:members.map(q=>q.id).join(','),hash:hash(members.map(editorialHash).join('\n')),facts:members.map(q=>q.factKey).join(','),decision:'distinct',reason:reasons[entity]});}
const scan=JSON.parse(fs.readFileSync(path.join(data,'similarity_scan.json'),'utf8'));
const decisions=JSON.parse(fs.readFileSync(path.join(data,'editorial_decisions.json'),'utf8'));
function review(list){return list.map(c=>{const d=decisions[c.pair];if(!d||d.hash!==c.hash||!d.reason)throw Error('Unreviewed/stale '+c.pair);return{pair:c.pair,hash:c.hash,decision:'distinct',reason:d.reason};});}
csv('near_duplicate_review.csv',review(scan.internal),['pair','hash','decision','reason']);
csv('cross_bank_review.csv',review(scan.cross),['pair','hash','decision','reason']);
csv('editorial_review.csv',rows.map(q=>({id:q.id,hash:editorialHash(q),factKey:q.factKey,source:q.source,evidenceVerified:'yes',translationParity:'yes',difficultyReviewed:'yes',distinctFact:'yes',reviewDate:'2026-10-07'})),['id','hash','factKey','source','evidenceVerified','translationParity','difficultyReviewed','distinctFact','reviewDate']);
csv('fact_family_review.csv',families,['entity','ids','hash','facts','decision','reason']);
