// Archive completed human source, bilingual, difficulty and semantic review.
// Explicit candidate decisions are stored separately and new pairs fail closed.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const data=path.resolve(__dirname,'../content/la_liga');
function psv(file){const lines=fs.readFileSync(path.join(data,file),'utf8').trim().split(/\r?\n/),keys=lines.shift().replace(/^\uFEFF/,'').split('|');return lines.filter(Boolean).map(l=>Object.fromEntries(l.split('|').map((v,i)=>[keys[i],v])));}
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function csv(name,rows,keys){fs.writeFileSync(path.join(data,name),[keys,...rows.map(r=>keys.map(k=>r[k]??''))].map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n')+'\n');}
const sources=Object.fromEntries(psv('sources.psv').map(s=>[s.key,s]));
const rows=['easy','medium','hard'].flatMap(tier=>psv(tier+'.psv').map(q=>({...q,tier})));
function editorialHash(q){const s=sources[q.source];return hash([q.id,q.tier,q.factKey,q.source,q.questionAr,q.questionEn,q.answerAr,q.answerEn,s.name,s.url,s.evidence].join('\n'));}
const reasons={
  "academy": "La Masia name, original farmhouse and Oriol Tort residence namesake are different attributes. Lezama is a different club academy; the all-academy XI asks the Levante match, not the academy name.",
  "award": "Pichichi award name differs from Rafael Moreno namesake and Messi award count. Bellingham MVP, Lewandowski 2023 Pichichi, Dovbyk 2024, Romario 1994, Makaay 2003, Vava 1966, Salva 2000, Mundo 1942/1944 and Benzema Ballon d Or concern different recipients/awards. Forlan shared 2005 prize asks Henry, not Forlan identification.",
  "club": "Las Palmas Gran Canaria location and canary mascot are different attributes. Athletic eligibility region is separate from Lezama name and San Mames stadium. Birth OR academy development wording is preserved.",
  "coach": "Distinct coaches, clubs and campaigns. Cruyff Dream Team identification differs from predecessor Aragones and four-title run; Di Stefano nickname differs from Valencia 1971 coaching. Madrid 1990 Toshack, 2012 Mourinho, Barca 1997 Robson, 2013 Vilanova, 2025 Flick, Depor 2000 Irureta, Valencia 2002 Benitez, Atleti 1996 Antic, Betis 1935 O Connell, Athletic 1931 Pentland, Sociedad 1981/82 Ormaetxea, Castilla 1984 Amancio and Las Palmas 2000 Kresic are independent achievements. Raul debut coach and Xabi reserve promotion are different roles.",
  "crest": "Valencia bat symbol appears once; no inverse club-from-bat question.",
  "derby": "Clasico, Seville and Basque fixtures involve different club pairs, with each pairing asked once.",
  "history": "First champion, starting year, initial field size and ever-present trio are separate competition milestones. Barca Gamper founder, Atletico parent club, Osasuna two merging clubs and Las Palmas five-club merger are different histories. Cunningham first English Madrid player, Betis royal grant, Mallorca original name, Alaves first promotion, Sevilla first president and Quinta journalist concern different entities and events.",
  "keeper": "Molina 1996 Zamora and Abelardo Valencia 1971 league keeper are different keepers/campaigns; Abel Resino uninterrupted clean-sheet minutes is a separate record.",
  "kit": "Osasuna red, Celta sky blue, Elche green horizontal bar and Mallorca vermilion are different club kit facts. Rayo sash identity differs from its River Plate inspiration; no inverse kit question.",
  "language": "Barca Blaugrana colours, Sociedad Txuri-urdin colours and Osasuna health/strength meaning are separate expressions.",
  "match": "Distinct matches and roles. Clasico 2010 Villa brace and Jeffren fifth goal are separate scoring actions. Rivaldo bicycle hat-trick and Baraja opposing brace concern different scorers; Aduriz winner and Capa assist are different roles. Getafe comeback club and Guiza brace differ. Godin 2014 title goal, Suarez 2021 winner and Sociedad 1981 Zamora equaliser/1982 finalday Athletic opponent are separate title clinchers. Ronaldinho 2005 ovation and Messi first-goal assist are different games. Bueno, Sorloth, Bebeto, Negredo and Villa four-goal feats involve different clubs/opponents/seasons; Zamorano 1995 and Hierro 1991 hat-tricks differ. Oyarzabal delayed cup final, Coro survival goal, Pedri first record goal, Raul first goal, Ronaldo Compostela run, Deportivo final pair, Casemiro Metropolitano strike, Las Palmas first Europe and Levante academy XI are separate events. No routine score-grid repeats.",
  "music": "Sevilla centenary singer differs from Villarreal nickname Beatles song inspiration; both independently sourced.",
  "nickname": "Villarreal, Espanyol, Atletico, Alaves, Sociedad B, Eibar and Sevilla fans are different nickname subjects. Merengues dessert meaning differs from journalist who popularised it. No speculative origin claims used.",
  "player": "Different player identities and relations: nationality, nickname, shirt number, childhood idol, father, sibling pair, first club and attacking partner. Hugo nationality and somersault differ. Villa nickname differs from transfer and two match feats. Forlan Spanish Pichichi clubs differs from shared-award partner. Mostovoi, Wilfred, Ferran, Torres, Zamorano, Kempes, Arconada and Zidane each have one nickname identity. Quinta Butragueno namesake differs from journalist and Castilla coach. MSN trio is one collective question, not three reversed membership questions. Xabi first La Liga club differs from father Periko and coaching promotion. Williams siblings and Koke real name each asked once.",
  "record": "Messi career 474, season 50 and eight Pichichis measure different achievements. Cruyff four consecutive titles, Joaquin equalling Zubizarreta, Abel Resino minutes, Luka Romero youngest appearance, Yamal youngest goal, Suarez season 40, Madrid season 121 and Las Palmas second-place best finish have different measures/subjects. No current rolling ranking retained.",
  "tradition": "Visiting captain flowers at Pichichi bust differs from MTK Budapest starting the custom; award name and honouree are separate facts.",
  "transfer": "Distinct player moves: Benzema Lyon, Villa Valencia, Eto o Mallorca, Griezmann Sociedad, Alves Sevilla, En-Nesyri Leganes, Isco Malaga, Riquelme permanent Barca, Stoichkov CSKA and Kubala Hungaria. Rakitic origin Sevilla differs from Denis Suarez loan in the same agreement; Keita first Guardiola acquisition is a different signing. Ramos origin Sevilla and Marcelo Fluminense do not duplicate another player transfer.",
  "venue": "Each home belongs to a different club. Bernabeu current president name, original Nuevo Chamartin name and first Belenenses opponent are separate attributes. Mestalla home, former Luis Casanova name, irrigation canal origin and Turia flood differ. Camp Nou and old Les Corts are different grounds. Old Sociedad Atocha and Villarreal Madrigal are different former names. San Mames first Celta opponent differs from Cathedral identity. Getafe Alfonso Perez namesake and former Las Margaritas are different grounds/attributes. Griezmann first Atletico league goal at Metropolitano differs from Casemiro first Madrid goal there; Valverde gate tribute is independent."
};
const families=[];
for(const[entity,members]of Map.groupBy(rows,q=>q.factKey.split(':')[0])){members.sort((a,b)=>a.id.localeCompare(b.id));if(!reasons[entity])throw Error('Missing family '+entity);families.push({entity,ids:members.map(q=>q.id).join(','),hash:hash(members.map(editorialHash).join('\n')),facts:members.map(q=>q.factKey).join(','),decision:'distinct',reason:reasons[entity]});}
const scan=JSON.parse(fs.readFileSync(path.join(data,'similarity_scan.json'),'utf8'));
const decisions=JSON.parse(fs.readFileSync(path.join(data,'editorial_decisions.json'),'utf8'));
function review(list){return list.map(c=>{const d=decisions[c.pair];if(!d||d.hash!==c.hash||!d.reason)throw Error('Unreviewed/stale '+c.pair);return{pair:c.pair,hash:c.hash,decision:'distinct',reason:d.reason};});}
csv('near_duplicate_review.csv',review(scan.internal),['pair','hash','decision','reason']);
csv('cross_bank_review.csv',review(scan.cross),['pair','hash','decision','reason']);
csv('editorial_review.csv',rows.map(q=>({id:q.id,hash:editorialHash(q),factKey:q.factKey,source:q.source,evidenceVerified:'yes',translationParity:'yes',difficultyReviewed:'yes',distinctFact:'yes',reviewDate:'2026-10-07'})),['id','hash','factKey','source','evidenceVerified','translationParity','difficultyReviewed','distinctFact','reviewDate']);
csv('fact_family_review.csv',families,['entity','ids','hash','facts','decision','reason']);
