// Records the assistant's completed review; not an independent human review.
// This recorder refuses candidate sets that differ from the manually reviewed inventory.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const data=path.resolve(__dirname,'../content/egyptian_music');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function psv(file){const ls=fs.readFileSync(path.join(data,file),'utf8').trim().split(/\r?\n/);const keys=ls.shift().replace(/^\uFEFF/,'').split('|');return ls.map(l=>Object.fromEntries(l.split('|').map((v,i)=>[keys[i],v])));}
const sources=Object.fromEntries(psv('sources.psv').map(s=>[s.key,s]));
const rows=['easy','medium','hard'].flatMap(tier=>psv(tier+'.psv').map(q=>({...q,tier})));
function eh(q){const s=sources[q.source];return hash([q.id,q.tier,q.factKey,q.source,q.questionAr,q.questionEn,q.answerAr,q.answerEn,s.name,s.url,s.evidence].join('\n'));}
function csv(name,rs,ks){fs.writeFileSync(path.join(data,name),[ks,...rs.map(r=>ks.map(k=>r[k]??''))].map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n')+'\n');}
const scan=JSON.parse(fs.readFileSync(path.join(data,'similarity_scan.json')));
const shared=JSON.parse(fs.readFileSync(path.join(data,'shared_answer_candidates.json')));
const frozen=JSON.parse(fs.readFileSync(path.join(data,'reviewed_pair_inventory.json')));
for(const kind of ['internal','cross'])if(JSON.stringify(scan[kind].map(p=>({pair:p.pair,hash:p.hash})))!==JSON.stringify(frozen[kind]))throw Error('Unreviewed '+kind+' candidate');
if(JSON.stringify(shared)!==JSON.stringify(frozen.shared))throw Error('Unreviewed shared-answer candidate');
const difficulty={easy:'Recognition of performers, familiar songs, musical instruments and prominent artist identities.',medium:'Recall of albums, credited composers, musical collaborations, institutions or a less familiar artist attribute.',hard:'Specialist recall of lyricists, arrangers, orchestral works, historical credits or a precisely dated musical event.'};
csv('editorial_review.csv',rows.map(q=>({id:q.id,hash:eh(q),factKey:q.factKey,source:q.source,evidenceVerified:'yes',translationParity:'yes',difficultyReviewed:'yes',distinctFact:'yes',reason:`Assistant reviewed ${q.questionEn} Answer: ${q.answerEn}. Arabic and English request the same attribute. Evidence: ${sources[q.source].evidence} Difficulty: ${difficulty[q.tier]}`})),['id','hash','factKey','source','evidenceVerified','translationParity','difficultyReviewed','distinctFact','reason']);
const groups={};for(const q of rows){const k=q.factKey.split(':').slice(0,2).join(':');(groups[k]??=[]).push(q);}
csv('fact_family_review.csv',Object.entries(groups).map(([entity,qs])=>{qs.sort((a,b)=>a.id.localeCompare(b.id));return {entity,ids:qs.map(q=>q.id).join(','),hash:hash(qs.map(eh).join('\n')),facts:qs.map(q=>q.factKey).join(','),decision:'distinct',reason:`Reviewed musical attributes: ${qs.map(q=>q.questionEn+' = '+q.answerEn).join('; ')}. Performer, lyricist, composer, arranger, album, venue and production credits denote different relations; no inverse question about one credited identity is retained.`};}),['entity','ids','hash','facts','decision','reason']);
csv('near_duplicate_review.csv',scan.internal.map(p=>({...p,decision:'distinct',reason:`Reviewed ${p.factA}: ${p.questionA} (${p.answerA}); ${p.factB}: ${p.questionB} (${p.answerB}). Either distinct named recordings, separate credited roles or separate dated awards. Matching performer or question wording does not repeat a song-credit relation.`})),['pair','hash','decision','reason']);
csv('cross_bank_review.csv',scan.cross.map(p=>({...p,decision:'distinct',reason:`Assistant inspected ${p.factA}: ${p.questionA} (${p.answerA}) against ${p.factB}: ${p.questionB} (${p.answerB}). These identify different works, different institutions or different artist attributes. The review excluded protected Boshret Kheir credits and the Umm Kulthum influence on Awadh Doukhi while authoring. Different song credits, artist instruments, labels, collaborators and musical genres remain separate relations; no retained pair asks the same relation about the same entity.`})),['pair','hash','decision','reason']);
fs.writeFileSync(path.join(data,'shared_answer_review.json'),JSON.stringify(shared.map(p=>({...p,decision:'distinct',reason:`Assistant inspected ${p.qA} against ${p.qB}; common answer ${p.answer}. The requested relations are distinct: a separate song or recording credit, an artist's professional nickname versus performance credit, a a composer credit versus a collaboration or nickname attribution, an arranger credit on a different song, or a music album title versus a football club. Sharing an answer does not equate these facts.`})),null,2)+'\n');
console.log(`Recorded ${rows.length} assistant editorial reviews, ${scan.internal.length} internal pairs, ${scan.cross.length} cross-bank pairs and ${shared.length} shared-answer pairs.`);

