// Records the assistant's completed factual, bilingual and semantic review.
// This is not an independent human review. Candidate hashes must match the frozen inventory.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const data=path.resolve(__dirname,'../content/football_legends');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function psv(file){const lines=fs.readFileSync(path.join(data,file),'utf8').trim().split(/\r?\n/),keys=lines.shift().replace(/^\uFEFF/,'').split('|');return lines.filter(Boolean).map(l=>Object.fromEntries(l.split('|').map((v,i)=>[keys[i],v])));}
const sources=Object.fromEntries(psv('sources.psv').map(s=>[s.key,s]));
const rows=['easy','medium','hard'].flatMap(tier=>psv(tier+'.psv').map(q=>({...q,tier})));
function eh(q){const s=sources[q.source];return hash([q.id,q.tier,q.factKey,q.source,q.questionAr,q.questionEn,q.answerAr,q.answerEn,s.name,s.url,s.evidence].join('\n'));}
function csv(name,rs,ks){fs.writeFileSync(path.join(data,name),[ks,...rs.map(r=>ks.map(k=>r[k]??''))].map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n')+'\n');}
const frozen=JSON.parse(fs.readFileSync(path.join(data,'reviewed_pair_inventory.json')));
const scan=JSON.parse(fs.readFileSync(path.join(data,'similarity_scan.json')));
const shared=JSON.parse(fs.readFileSync(path.join(data,'shared_answer_candidates.json')));
for(const kind of ['internal','cross'])if(JSON.stringify(scan[kind].map(p=>({pair:p.pair,hash:p.hash})))!==JSON.stringify(frozen[kind]))throw Error('Unreviewed '+kind+' candidate');
if(JSON.stringify(shared)!==JSON.stringify(frozen.shared))throw Error('Unreviewed shared-answer candidate');
const tiers={easy:'Accessible recognition of a famous nickname, player, celebration or major honour.',medium:'Moderate recall of an international final, award, career milestone or notable achievement.',hard:'Specialist recall of an older match contribution, obscure career connection, precise incident or less familiar historical role.'};
csv('editorial_review.csv',rows.map(q=>({id:q.id,hash:eh(q),factKey:q.factKey,source:q.source,evidenceVerified:'yes',translationParity:'yes',difficultyReviewed:'yes',distinctFact:'yes',reason:`Assistant reviewed ${q.questionEn} Answer: ${q.answerEn}. Arabic asks the same fact with equivalent answer. Evidence: ${sources[q.source].evidence} ${tiers[q.tier]}`})),['id','hash','factKey','source','evidenceVerified','translationParity','difficultyReviewed','distinctFact','reason']);
const groups={};for(const q of rows){const k=q.factKey.split(':').slice(0,2).join(':');(groups[k]??=[]).push(q);}
csv('fact_family_review.csv',Object.entries(groups).map(([entity,qs])=>{qs.sort((a,b)=>a.id.localeCompare(b.id));return {entity,ids:qs.map(q=>q.id).join(','),hash:hash(qs.map(eh).join('\n')),facts:qs.map(q=>q.factKey).join(','),decision:'distinct',reason:`Reviewed player relations: ${qs.map(q=>q.questionEn+' = '+q.answerEn).join('; ')}. Nickname, dated match action, annual award, biographical connection and coaching role are separate attributes. Same-player membership alone is not repeated factual content.`};}),['entity','ids','hash','facts','decision','reason']);
csv('near_duplicate_review.csv',scan.internal.map(p=>({...p,decision:'distinct',reason:`Reviewed ${p.factA}: ${p.questionA} (${p.answerA}); ${p.factB}: ${p.questionB} (${p.answerB}). Different dated event, credited role, award or biographical attribute. Where the event is shared, the requested contributor differs; these are not inverse questions about one identity.`})),['pair','hash','decision','reason']);
csv('cross_bank_review.csv',scan.cross.map(p=>({...p,decision:'distinct',reason:`Reviewed ${p.questionA} (${p.answerA}) against ${p.questionB} (${p.answerB}). The explicitly stated event, edition, competition, award or player attribute differs. No identical requested event attribute remains after replacing the detected repeated facts.`})),['pair','hash','decision','reason']);
fs.writeFileSync(path.join(data,'shared_answer_review.json'),JSON.stringify(shared.map(p=>({...p,decision:'distinct',reason:p.pair==='football_legends_v2_136/bundesliga_v2_200'?'Julio Cesar Soares Espindola won the 2013 goalkeeper award; Julio Cesar da Silva scored Dortmund\'s 1995 goal. These are different people with the same short name.':p.pair==='football_legends_v2_032/world_cup_v2_013'?'Modric won the annual France Football Ballon d\'Or and the separate FIFA World Cup Golden Ball in 2018. Different awarding bodies, scope and trophies.':p.pair==='football_legends_v2_197/ligue_1_v2_036'?'A specific 2005 farewell match venue is distinct from identifying Marseille\'s home stadium.':`Reviewed common answer ${p.answer}: ${p.qA} versus ${p.qB}. The questions request separate dated actions, honours, career attributes or club relationships; the shared answer does not identify the same underlying relation.`})),null,2)+'\n');
console.log('Recorded 204 assistant editorial reviews and the frozen semantic comparisons.');
