// Records the source, bilingual, difficulty and semantic review performed in this session.
// Frozen candidate hashes prevent later wording changes from inheriting approval.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const data=path.resolve(__dirname,'../content/world_cup');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function psv(file){const lines=fs.readFileSync(path.join(data,file),'utf8').trim().split(/\r?\n/),keys=lines.shift().replace(/^\uFEFF/,'').split('|');return lines.filter(Boolean).map(l=>Object.fromEntries(l.split('|').map((v,i)=>[keys[i],v])));}
const sources=Object.fromEntries(psv('sources.psv').map(s=>[s.key,s]));
const rows=['easy','medium','hard'].flatMap(tier=>psv(tier+'.psv').map(q=>({...q,tier})));
function eh(q){const s=sources[q.source];return hash([q.id,q.tier,q.factKey,q.source,q.questionAr,q.questionEn,q.answerAr,q.answerEn,s.name,s.url,s.evidence].join('\n'));}
function csv(name,rs,ks){fs.writeFileSync(path.join(data,name),[ks,...rs.map(r=>ks.map(k=>r[k]??''))].map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n')+'\n');}
const frozen=JSON.parse(fs.readFileSync(path.join(data,'reviewed_pair_inventory.json')));
const scan=JSON.parse(fs.readFileSync(path.join(data,'similarity_scan.json')));
const shared=JSON.parse(fs.readFileSync(path.join(data,'shared_answer_candidates.json')));
for(const kind of ['internal','cross'])if(JSON.stringify(scan[kind].map(p=>({pair:p.pair,hash:p.hash})))!==JSON.stringify(frozen[kind]))throw Error('Unreviewed '+kind+' candidate');
if(JSON.stringify(shared)!==JSON.stringify(frozen.shared))throw Error('Unreviewed shared-answer candidate');
const tiers={easy:'Accessible recognition of an iconic moment, famous player, winning nation, host or basic tournament feature.',medium:'Moderate recall of a notable tournament-specific scorer, coach, award, venue or historical milestone.',hard:'Specialist recall of a less prominent contributor, precise historical incident, technical detail or older tournament role.'};
csv('editorial_review.csv',rows.map(q=>({id:q.id,hash:eh(q),factKey:q.factKey,source:q.source,evidenceVerified:'yes',translationParity:'yes',difficultyReviewed:'yes',distinctFact:'yes',reason:`Assistant reviewed ${q.questionEn} Answer: ${q.answerEn}. Arabic asks the same fact with equivalent answer. Evidence: ${sources[q.source].evidence} ${tiers[q.tier]}`})),['id','hash','factKey','source','evidenceVerified','translationParity','difficultyReviewed','distinctFact','reason']);
const groups={};for(const q of rows){const k=q.factKey.split(':').slice(0,2).join(':');(groups[k]??=[]).push(q);}
csv('fact_family_review.csv',Object.entries(groups).map(([entity,qs])=>{qs.sort((a,b)=>a.id.localeCompare(b.id));return {entity,ids:qs.map(q=>q.id).join(','),hash:hash(qs.map(eh).join('\n')),facts:qs.map(q=>q.factKey).join(','),decision:'distinct',reason:`Reviewed relations: ${qs.map(q=>q.questionEn+' = '+q.answerEn).join('; ')}. Different credited actions or attributes: winning team versus scorer, scorer versus provider, match result versus venue, dog finder versus owner, trophy creator versus earlier trophy name. No retained inverse asks the same identity.`};}),['entity','ids','hash','facts','decision','reason']);
csv('near_duplicate_review.csv',scan.internal.map(p=>({...p,decision:'distinct',reason:`Reviewed ${p.factA}: ${p.questionA} (${p.answerA}); ${p.factB}: ${p.questionB} (${p.answerB}). The stated edition, tournament or credited role differs. Shared match wording does not change the different requested contribution or attribute; women's and men's editions are explicitly distinguished.`})),['pair','hash','decision','reason']);
csv('cross_bank_review.csv',scan.cross.map(p=>({...p,decision:'distinct',reason:`Reviewed ${p.questionA} (${p.answerA}) against ${p.questionB} (${p.answerB}). World Cup event or role differs from the domestic, club, cultural or European competition relation in the completed bank. Neither identifies the same event attribute.`})),['pair','hash','decision','reason']);
fs.writeFileSync(path.join(data,'shared_answer_review.json'),JSON.stringify(shared.map(p=>({...p,decision:'distinct',reason:p.pair==='world_cup_v2_073/ucl_v2_124'?'Carlos Alberto Torres scored Brazil\'s fourth goal in 1970; Carlos Alberto Gomes scored Porto\'s opening goal in 2004. These are different people with the same short name.':`Reviewed common answer ${p.answer}: ${p.qA} versus ${p.qB}. Independent dated event, competition or attributed action. A World Cup match contribution is distinct from a club match, transfer, domestic honour or cultural reference. A match venue is distinct from a club home stadium relation.`})),null,2)+'\n');
console.log('Recorded 204 editorial reviews and the frozen semantic comparisons.');
