const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..'),dir=path.join(root,'content/bundesliga');
const scan=JSON.parse(fs.readFileSync(path.join(dir,'similarity_scan.json'),'utf8'));
const internal={'002/090':'Gerd Muller holds the full-league career goal record; Kirsten holds the separate Leverkusen club record. Different populations and totals.','007/020':'Gladbach Foals and Leipzig Red Bulls identify independent clubs and nicknames.','110/130':'Veh won Stuttgart 2007; Daum won Stuttgart 1992. Different coaches and title campaigns.'};
const crossReasons={nickname:'Different club identities and nicknames; no Bundesliga nickname is repeated as an inverse question.',stadium:'Different clubs, stadiums and stadium attributes.',record:'Independent league or club records with different players, competitions and numerical totals.',stuttgart1992:'Daum coached Stuttgart in 1992; the other question concerns a different club, coach and championship.',stpauli:'Millerntor is St Pauli stadium in Hamburg; the other is a different club stadium.',derby:'The Revierderby and Merseyside derby have different club pairings and locations.',kit:'Stuttgart red chest hoop and Elche green chest stripe are independent club kit identities.',bayern2013:'Thiago joined Bayern from Barcelona in 2013; Isco joined Madrid from Malaga. Different players and moves.',wirtz:'Wirtz won Germany 2023/24 player award; Bellingham won Spain award. Different domestic competitions and recipients.',lewandowski:'Lewandowski Lech-to-Dortmund in 2010 differs from Villa Valencia-to-Barcelona and Cavani Palermo-to-Napoli.',final:'Ozil scored Bremen 2009 cup winner; the other concerns a different competition, match, club and scorer.',mascot:'Frankfurt eagle Attila and Lazio eagle Olympia are different live birds and clubs introduced in different years.',fortuna:'Zewe holds Fortuna league appearances record; Zanetti holds Inter all-competition appearances record.',rule:'Germany introduced three points in 1995/96; Italy in 1994/95. Different national rule changes.'};
const decisions={};for(const c of scan.internal){const key=c.pair.replaceAll('bundesliga_v2_','');if(!internal[key])throw Error('Review required '+key);decisions[c.pair]={hash:c.hash,reason:internal[key]};}
for(const c of scan.cross){const key=c.factA.split(':')[0],r=crossReasons[key];if(!r||c.answerA===c.answerB)throw Error('Review required '+c.pair);decisions[c.pair]={hash:c.hash,reason:r+' Compared facts: '+c.factA+' / '+c.factB+'.'};}
fs.writeFileSync(path.join(dir,'editorial_decisions.json'),JSON.stringify(decisions,null,2)+'\n');
const shared=JSON.parse(fs.readFileSync(path.join(dir,'shared_answer_candidates.json'),'utf8'));
const reasons={'014':'Stuttgart shirt hoop differs from Kuwait flag bottom stripe and Osasuna shirt.','004':'Bayern eleven German titles differs from Karimi Al Ahli-to-Bayern transfer.','018':'Leverkusen Factory XI nickname differs from Azmoun departure to UAE and Son transfer to Spurs.','093':'Liverpool as Augsburg European knockout opponent differs from Assaidi transfer and Gerrard career club.','172':'Wolfsburg as Robben-Ribery first joint opponent differs from Grafite transfer origin.','010':'Klopp Dortmund titles 2011/12 differ from Liverpool 2020 title.','029':'Haaland Dortmund debut hat-trick differs from City season record and meditation celebration.','036':'Tottenham Kane transfer origin differs from Cantona hat-trick opponent.','124':'Chelsea academy Musiala origin differs from Salah senior Chelsea spell.','003':'Alonso Leverkusen title differs from Sociedad reserves promotion.','016':'Flick Bayern sextuple differs from Barcelona league 2025.','033':'Lewa Bayern five goals in nine minutes differs from Barcelona first-season scoring award.','062':'Thiago Barcelona-to-Bayern differs from Riquelme and Maradona moves and Barcelona first title.','088':'Makaay Phantom nickname differs from Deportivo Golden Shoe.','096':'Hertha Old Lady nickname differs from Las Palmas European opponent.','123':'Bellingham Dortmund captaincy record differs from Madrid award.','129':'Espanyol Leverkusen final opponent differs from nickname and Hierro hat-trick opponent.','194':'Makaay Bayern 3000th goal differs from Deportivo Golden Shoe.','058':'Klose somersault nickname differs from Lazio five-goal match.'};
fs.writeFileSync(path.join(dir,'shared_answer_review.json'),JSON.stringify(shared.map(c=>{const id=c.pair.split('/')[0].slice(-3);if(!reasons[id])throw Error('Shared review required '+c.pair);return {...c,decision:'distinct',reason:reasons[id]};}),null,2)+'\n');
let script=fs.readFileSync(path.join(root,'tool/record_serie_a_editorial_review.js'),'utf8').replaceAll('serie_a','bundesliga');
const lines=['easy','medium','hard'].flatMap(t=>fs.readFileSync(path.join(dir,t+'.psv'),'utf8').trim().split(/\r?\n/).slice(1).map(l=>l.split('|')));
const family={};for(const [k,rows]of Map.groupBy(lines,q=>q[1].split(':')[0]))family[k]='Reviewed individual facts: '+rows.map(q=>q[1]).join('; ')+'. Different relations, individuals, events or attributes; no reversed questions. Shared-event roles (Bayer 1988 opponent, aggregate equaliser, goalkeeper; Bayern 2001 scorer and opposing goalkeeper) were compared explicitly and ask independent contributions. Player identities, nicknames, academy origins and later achievements were compared across families.';
script=script.replace(/const reasons=\{[\s\S]*?\n\};/,'const reasons='+JSON.stringify(family,null,2)+';');fs.writeFileSync(path.join(root,'tool/record_bundesliga_editorial_review.js'),script);
